package:
  name: geneseekr
  version: "0.1.1"

source:
  git_url: https://github.com/OLC-Bioinformatics/GeneSeekr

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - olctools
    - click
    - biopython
    - xlsxwriter
    - blast
    - numpy
  run:
    - python
    - olctools
    - click
    - biopython
    - xlsxwriter
    - blast
    - numpy

about:
  home: https://github.com/OLC-Bioinformatics/GeneSeekr
  license: MIT
  license_file: LICENSE
